
trigger:
- main

stages:
  - stage: Build
    pool:
      vmImage: 'windows-latest'
    jobs:
    - job: Build
      displayName: 'Powershell Script Execute'
      steps:
        - task: PowerShell@2
          displayName: 'Run Powershell Build'
          inputs:
            targetType: 'inline'
            script: '.\azureoperationsscript.ps1 -OrganizationUrl $(OrganizationUrl) -PAT $(PAT) -OrganizationName $(OrganizationName)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: 'D:\a\1\s\allprojnameid.csv'
            ArtifactName: 'drop'
            publishLocation: 'Container'
